language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.0
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - android-25
script:
  - ./gradlew build 
after_failure:
  - cat app/build/reports/checkstyle.html
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
  - cat app/build/reports/findbugs.html
  - cat app/build/reports/pmd.html
