language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=25
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - tools
    - android-${ANDROID_API_LEVEL}
    - sys-img-armeabi-v7a-android-${ANDROID_API_LEVEL}
